# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :z do
    # add actions here: https://docs.fastlane.tools/actions
    gym(
    # 每次打包之前clean一下
    clean: true,
    # output_directory: './fastlane/release',
    # output_name: 'smartowon.ipa',
    # scheme: "Runner",
    # configuration: 'Release',
    # include_bitcode: false,
    # include_symbols: true,
    export_method: 'development',
    # export_xcargs: '-allowProvisioningUpdates'
)

  end



end
